# https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/olivere/elastic"
  version = "6.1.23"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"
